---
title: "Mod3 Classification Regression"
author: "Elizabeth Angelo"
date: "2024-02-27"
output: word_document
---

```{r}
library(readr)
parole <- read_csv("~/Desktop/BAN 502/Module 3/Mod3Assign1 Log Reg/parole.csv")
```

```{r}
library(tidyverse)
library(tidymodels)
library(e1071)
library(ROCR)
```

```{r}
parolefactor <- parole %>%
  mutate(
    male = factor(male, levels = c(0, 1), labels = c("Female", "Male")),
    race = factor(race, levels = c(1,2), labels = c("White", "Other")),
    state = factor(state),
    crime = factor(crime),
    multiple.offenses = factor(multiple.offenses, levels = c(0, 1), labels = c("No", "Yes")),
    violator = factor(violator, levels = c(0, 1), labels = c("No", "Yes"))
  )
parolefactor

```
```{r Q1}
violated_count <- sum(parolefactor$violator == "Yes")
violated_count
```

```{r}
set.seed(12345)

split_data <- initial_split(parolefactor, prop = 0.7, strata = "violator")

train <- training(split_data)
test <- testing(split_data)

table(train$violator)

```

```{r}
male <- ggplot(parolefactor, aes(x = male, fill = violator)) +
  geom_bar(position = "stack") +
  labs(title = "Distribution of Violators by Gender", x = "Gender", y = "Count")
male


state <- ggplot(parolefactor, aes(x = state, fill = violator)) +
  geom_bar(position = "stack") +
  labs(title = "Distribution of Violators by State", x = "State", y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
state

sentence <- ggplot(parolefactor, aes(x = violator, y = max.sentence, fill = violator)) + geom_boxplot() +
  labs(title = "Violation Rates by Max Sentence Duration", x = "Violator", y = "Max Sentence Duration") +
  scale_fill_manual(values = c("No" = "lightblue", "Yes" = "salmon"))
sentence
```

```{r}
parole_recipe = recipe(violator ~ state, train)

parole_model = 
  logistic_reg() %>%
  set_engine("glm")

logref_wf = workflow() %>%
  add_recipe(parole_recipe) %>%
  add_model(parole_model)

parole_fit = fit(logref_wf, train)
```

```{r}
summary(parole_fit$fit$fit$fit)
```

```{r}
parole_recipe2 = recipe(violator ~ state + multiple.offenses + race, train) %>%
  step_dummy(all_nominal(), -all_outcomes())

parole_model2 = 
  logistic_reg() %>%
  set_engine("glm")

logref_wf2 = workflow() %>%
  add_recipe(parole_recipe2) %>%
  add_model(parole_model2)

parole_fit2 = fit(logref_wf2, train)
```

```{r}
parolee1 = data.frame(state = "3", multiple.offenses = "Yes", race = "White")

pred1= predict(parole_fit2, parolee1, type="prob")

pred1

predictions = predict(parole_fit2, train, type="prob") [2]
head(predictions)

ROCRpred = prediction(predictions, train$violator)

ROCRperf = performance(ROCRpred, "tpr", "fpr")
plot(ROCRperf, colorize=TRUE, print.cutoffs.at=seq(0,1,by=0.1), text.adj=c(-0.2,1.7))

as.numeric(performance(ROCRpred, "auc")@y.values)

opt.cut = function(perf, pred){
  cut.ind = mapply(FUN=function(x, y, p){
    d = (x - 0)^2 + (y - 1)^2
    ind = which(d == min(d))
    c(sensitivity = y[[ind]], specificity = 1-x[[ind]],
      cutoff = p[[ind]])
  }, perf@x.values, perf@y.values, pred@cutoffs)
}
print(opt.cut(ROCRperf, ROCRpred))
```


```{r}
t1 = table(train$violator, predictions > 0.2015788)
t1
```


```{r}
acc = (t1[1,1]+t1[2,2])/nrow(train)
sen = t1[2,2] / (t1[2,2] + t1[2,1])
spc = t1[1,1] / (t1[1,1] + t1[1,2])
```


```{r}
t1 = table(train$violator, predictions > 0.5)
(t1[1,1]+t1[2,2]) / nrow(train)
t1

t2 = table(train$violator, predictions > 0.6)
(t2[1,1]+t2[2,2]) / nrow(train)
t2

t3 = table(train$violator, predictions > 1)
(t3[1]) / nrow(train)
t3
```
























